FROM java:latest

WORKDIR /c/Users/c.mccoy/Desktop/file_folders/docker_files/first_java
ADD . /c/Users/c.mccoy/Desktop/file_folders/docker_files/first_java

RUN javac helloWorld.java
CMD ["java", "helloWorld"]
